### ISSUE TITLE
Using with Jitpack libraries doesn't compile

### ISSUE THREAD

**Issue by hannesa2** [Consti10/RenderingX#11]
Using with Jitpack libraries
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/3314607/151117593-51fa9d4d-f59f-4d10-8704-685013c622fd.png">

doesn't compile

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/3314607/151117517-ccf7166f-bc13-4314-9372-363ce307d5ef.png">

**Comment by hannesa2** [comment]
I recommend to add your https://github.com/Consti10/LiveVideo10ms as git submodule and introduce a flavor to with/out code

**Comment by Consti10** [comment]
Yeah, I was hoping that prefab would finally fix the multiple header path issue at some point, then I could properly use Jitpack to get both java and c++ dependencies from LiveVideo10ms. But prefab is still kinda experimental / doesn't receive much attention.

**Comment by hannesa2** [comment]
I even don't know _prefab_

**Comment by Consti10** [comment]
https://github.com/google/prefab

It would be so nice if thy finally fixed the bugs with it / made it an official project ;)

**Comment by hannesa2** [comment]
I could fix jitpack.io for https://github.com/Consti10/LiveVideo10ms
But to see issues immediate please use https://github.com/Consti10/RenderingX/pull/12 first. 
jitpack.io would be a second step

**Comment by Consti10** [comment]
The issue for me with submodules is that they would disrupt my work flow when working with FPV_VR. That's why I'd recommend
the "clone all into the same directory" aproach, then it should build without problems.

Argh I totally forgot, with that JitCi obviosly won't work on RenderingX ;/
I'l have a look.

**Comment by hannesa2** [comment]
Now you see your master is broken ...
<img width="587" alt="image" src="https://user-images.githubusercontent.com/3314607/151821824-68dd321e-29b4-4baf-9b3e-faa993fba914.png">

**Comment by Consti10** [comment]
I'l redo Jitpack for LiveVideo10ms, then look at RenderingX. Btw, I still have the stupid gvr dependency floating around in RenderingX, maybe cardboard has finally evolved such that I can get rid of it.

**Comment by Consti10** [comment]
It all used to work 1 year ago haha ;/

**Comment by Consti10** [comment]
> > the "clone all into the same directory" aproach, then it should build without problems.
> 
> I could merge `LiveVideo10ms` into `RenderingX` without loose any commit. But the result would be still a broken repo. Should I do it ?

This won't work out of the box, you'd also have to modify the include paths then. I am wondering why you can't build though, it is working right now locally on my windows machine with latest master of LiveVideo10ms and RenderingX in the same directory.

**Comment by hannesa2** [comment]
> I am wondering why you can't build though, it is working right now locally on my windows machine with latest master of LiveVideo10ms and RenderingX in the same directory.

That's the huge advantage of a CI. To avoid sentences like "it works on my machine" 😀

Yes, I could only merge this two remotes to one technically from git side. 
The includes would be your task.

**Comment by Consti10** [comment]
I know. that's what I had JitCi for. But for some reason it stopped working on all the 3 repos (LiveVideo10ms, RenderingX, FPV_VR_OS) ;)

**Comment by Consti10** [comment]
are you building on linux or windows ?

**Comment by hannesa2** [comment]
macOS

**Comment by Consti10** [comment]
So RenderingX has two dependencies on libraries from Livevideo10ms
1) VideoCore: There it only needs it as a java package, the c/c++ code comes with it
2) Shared: There some cpp header-only files are placed that are also needed to compile RenderingXCore/Example.
If you still have c++ build issues, you can modify the path here:
https://github.com/Consti10/RenderingX/blob/master/RenderingXCore/RenderingXCore.cmake#L10

**Comment by hannesa2** [comment]
Yes, I already played around here, but never found a valid solution.
The best place to show me the solution would be https://github.com/Consti10/RenderingX/pull/12
