### ISSUE TITLE
run time exception 

### ISSUE THREAD

**Issue by azizi436** [Consti10/RenderingX#4]
Hi 
i want to use Mediaplayer in **AEample360Video** class and when i call this class it give me an error like below : 
```
`   : Unable to start activity ComponentInfo{constantin.renderingx.example/constantin.renderingx.example.stereo.video360degree.AExample360Video}: java.lang.RuntimeException: Failed to call observer method

  Caused by: java.lang.IllegalArgumentException: configs == null
        at android.opengl.EGL14.eglChooseConfig(Native Method)
        at constantin.renderingx.core.mglview.XEGLConfigChooser.getExactMatch(XEGLConfigChooser.java:86)
        at constantin.renderingx.core.mglview.XEGLConfigChooser.chooseConfig(XEGLConfigChooser.java:66)
        at constantin.renderingx.core.mglview.XGLSurfaceView.onCreate(XGLSurfaceView.java:90)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)`
```
please check it and give me response
thanks

**Comment by pmsmasoud** [comment]
i have same problem   :|

**Comment by Consti10** [comment]
Hello,
Looks like I was a bit too quick pushing my recent changes where I replaced GLSurfaceView.
The quickest solution is to go for an older commit:
[Commit that should work](https://github.com/Consti10/RenderingX/tree/b98e950be6ccacfff2bbaf0ff57528e5206aa0d9)
I'l test the replacement code for GLSurfaceView on other devices (via firebase ) in the next days.

**Comment by Consti10** [comment]
@azizi436 
Can you share the device name and more of the android log with me ?

**Comment by azizi436** [comment]
@Consti10 
Ok thanks ,I solved my problem by replacing older **GlSurfaceView** instead of **glSurfaceView2** but i saw new problem , there is a gmail picture in the center of screen  . what is the problem ?!  check this link to see the picture of the bug [https://imgur.com/4ehYFFJ](url)

**Comment by azizi436** [comment]
> 
> 
> @azizi436
> Can you share the device name and more of the android log with me ?

**Comment by Consti10** [comment]
Hello,
you can remove the picture by removing its layer.
In [class](https://github.com/Consti10/RenderingX/blob/master/RenderingXExample/src/main/cpp/stereo/video360Degree/Renderer360Video.cpp)
just remove 
`vrCompositorRenderer.addLayer2DCanvas(-3,uiElementWidth,uiElementWidth*1080.0f/2160.0f,mExampleUiTexture,false,VrCompositorRenderer::FULL);`

**Comment by azizi436** [comment]
@Consti10 
it's ok...thanks for your helping 🥇
