### ISSUE TITLE
add RendringXCore to project

### ISSUE THREAD

**Issue by azizi436** [Consti10/RenderingX#5]
Hello 
I want to add **AExample360Video** to my project but after i added it, the **Renderer360Video** don't diagnosis something , like below : 

![probleem](https://user-images.githubusercontent.com/36598338/89028146-06e18780-d341-11ea-8724-91a02ed30425.png)

what is the problem ??

**Comment by Consti10** [comment]
This is native code called by java. You have to re-name the native function names according to your project name.

**Comment by azizi436** [comment]
How can i do this , can you give me more explain about it ?
I just changed this according to my project name (in the **Render360Video.cpp**) : 

![eree](https://user-images.githubusercontent.com/36598338/89099823-4d011e80-d407-11ea-8ca5-a176955e0ea3.png)
