### ISSUE TITLE
Change the background color

### ISSUE THREAD

**Issue by pmsmasoud** [Consti10/RenderingX#8]
Hello 
How can i change the background color of **AExample360Video** to my personal color ?

![ax](https://user-images.githubusercontent.com/41676858/89415022-8a83e580-d740-11ea-8989-f9cc3a5b3d3c.jpg)

it is red by default

**Comment by Consti10** [comment]
The red color comes from VrCompositorRenderer's 'occlusionMesh'
`const TrueColor occlusionMeshColor=ENABLE_DEBUG ? TrueColor2::RED : TrueColor2::BLACK;
    CardboardViewportOcclusion::uploadOcclusionMeshLeftRight(*this, occlusionMeshColor, mOcclusionMesh);`

Either set ENABLE_DEBUG to false or change the color manually

**Comment by pmsmasoud** [comment]
i want to use this color : 

![blue](https://user-images.githubusercontent.com/41676858/89426676-a773e500-d74f-11ea-97f4-7b561407c9e5.png)

Hex : 66b2b5 ( FF67B2B5 )
R:103
G:178
B:181

Can you give me it's **TrueColor**  like this : 

`    static constexpr const TrueColor RED=TrueColor(glm::vec4{1.0f, 0, 0, 1});
`

**Comment by Consti10** [comment]
`TrueColor CustomColor =TrueColor(103,178,181,255);`

**Comment by pmsmasoud** [comment]
دمت گرم سالار

**Comment by pmsmasoud** [comment]
بچه چه کردی؟

**Comment by pmsmasoud** [comment]
Ok thanks 👍
