### ISSUE TITLE
Release error

### ISSUE THREAD

**Issue by azizi436** [Consti10/RenderingX#9]
Hi 
I want to get a release from my app but it gave me an error like below : 
![err](https://user-images.githubusercontent.com/36598338/89691187-8fea5700-d91d-11ea-8f50-7babb408927a.png)

What is the reason? please help me

**Comment by Consti10** [comment]
I'd assume that you also need to delete the `stripXXX` stuff from the build config for release.

**Comment by Consti10** [comment]
I am going to move the '360° video activity' into the RenderingXCore module, such that you don't need to deal with native code anymore when adding it to your app.

**Comment by azizi436** [comment]
@Consti10 
ok thanks , but how can i remove `stripXXX` stuff from my buildconfig ?!
please explain more or with an example

**Comment by azizi436** [comment]
I also realized this error exist when i `rebuild project `even in debug : 

```
`Build command failed.
Error while executing process E:\GoogleAndroidStudio\SDK-NDK\android-sdk\cmake\3.10.2.4988404\bin\ninja.exe with arguments {-C D:\Ateriad\Titar\app\.cxx\cmake\debug\x86_64 GLPrograms Time example-2}
ninja: Entering directory ````
D:\Ateriad\Titar\app\.cxx\cmake\debug\x86_64'

ninja: error: 'D:/Ateriad/Titar/RenderingXCore/libs/google/gvr/jni/x86_64/libgvr.so', needed by '../../../../build/intermediates/cmake/debug/obj/x86_64/libGLPrograms.so', missing and no known rule to make it
```

**Comment by Consti10** [comment]
Great !
x86_64 is not supported by the gvr library - They did not bother about it since it is a really exotic platform.
